include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - ios/build/**
    - android/.cxx/**
    - example/**/build/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
