enum Country {
  afghanistan('Afghanistan', 'AF', 'AFG', '🇦🇫', 'assets/flags/af.png', 93, 10,
      10, "### ### ####"),
  albania('Albania', 'AL', 'ALB', '🇦🇱', 'assets/flags/al.png', 355, 9, 9,
      "## ### ###"),
  algeria('Algeria', 'DZ', 'DZA', '🇩🇿', 'assets/flags/dz.png', 213, 10, 10,
      "### ### ####"),
  andorra('Andorra', 'AD', 'AND', '🇦🇩', 'assets/flags/ad.png', 376, 6, 6,
      "## ## ## ##"),
  angola('Angola', 'AO', 'AGO', '🇦🇴', 'assets/flags/ao.png', 244, 9, 9,
      "### ### ###"),
  antiguaAndBarbuda('Antigua and Barbuda', 'AG', 'ATG', '🇦🇬',
      'assets/flags/ag.png', 268, 7, 7, "### ####"),
  argentina('Argentina', 'AR', 'ARG', '🇦🇷', 'assets/flags/ar.png', 54, 11, 11,
      "## #### ####"),
  armenia('Armenia', 'AM', 'ARM', '🇦🇲', 'assets/flags/am.png', 374, 8, 8,
      "## ### ###"),
  australia('Australia', 'AU', 'AUS', '🇦🇺', 'assets/flags/au.png', 61, 9, 9,
      "#### ### ###"),
  austria('Austria', 'AT', 'AUT', '🇦🇹', 'assets/flags/at.png', 43, 11, 11,
      "### #### ####"),
  azerbaijan('Azerbaijan', 'AZ', 'AZE', '🇦🇿', 'assets/flags/az.png', 994, 9,
      9, "### ### ## ##"),
  bahamas('Bahamas', 'BS', 'BHS', '🇧🇸', 'assets/flags/bs.png', 1, 10, 10,
      "### ####"),
  bahrain('Bahrain', 'BH', 'BHR', '🇧🇭', 'assets/flags/bh.png', 973, 8, 8,
      "#### ####"),
  bangladesh('Bangladesh', 'BD', 'BGD', '🇧🇩', 'assets/flags/bd.png', 880, 10,
      10, "### ### ####"),
  barbados('Barbados', 'BB', 'BRB', '🇧🇧', 'assets/flags/bb.png', 1, 7, 7,
      "### ####"),
  belarus('Belarus', 'BY', 'BLR', '🇧🇾', 'assets/flags/by.png', 375, 9, 9,
      "## ### ####"),
  belgium('Belgium', 'BE', 'BEL', '🇧🇪', 'assets/flags/be.png', 32, 9, 9,
      "## ## ## ##"),
  belize('Belize', 'BZ', 'BLZ', '🇧🇿', 'assets/flags/bz.png', 501, 7, 7,
      "#### ###"),
  benin('Benin', 'BJ', 'BEN', '🇧🇯', 'assets/flags/bj.png', 229, 8, 8,
      "## ## ## ##"),
  bhutan('Bhutan', 'BT', 'BTN', '🇧🇹', 'assets/flags/bt.png', 975, 8, 8,
      "17 ## ## ##"),
  bolivia('Bolivia', 'BO', 'BOL', '🇧🇴', 'assets/flags/bo.png', 591, 8, 8,
      "## #### ####"),
  bosniaAndHerzegovina('Bosnia and Herzegovina', 'BA', 'BIH', '🇧🇦',
      'assets/flags/ba.png', 387, 8, 8, "## ### ###"),
  botswana('Botswana', 'BW', 'BWA', '🇧🇼', 'assets/flags/bw.png', 267, 8, 8,
      "## ## ## ##"),
  brazil('Brazil', 'BR', 'BRA', '🇧🇷', 'assets/flags/br.png', 55, 11, 11,
      "## ##### #####"),
  brunei('Brunei', 'BN', 'BRN', '🇧🇳', 'assets/flags/bn.png', 673, 7, 7,
      "### ####"),
  bulgaria('Bulgaria', 'BG', 'BGR', '🇧🇬', 'assets/flags/bg.png', 359, 9, 9,
      "### ### ###"),
  burkinaFaso('Burkina Faso', 'BF', 'BFA', '🇧🇫', 'assets/flags/bf.png', 226,
      8, 8, "## ## ## ##"),
  burundi('Burundi', 'BI', 'BDI', '🇧🇮', 'assets/flags/bi.png', 257, 8, 8,
      "## ## ## ##"),
  cambodia('Cambodia', 'KH', 'KHM', '🇰🇭', 'assets/flags/kh.png', 855, 8, 8,
      "## ### ###"),
  cameroon('Cameroon', 'CM', 'CMR', '🇨🇲', 'assets/flags/cm.png', 237, 8, 8,
      "6 ## ## ## ##"),
  canada('Canada', 'CA', 'CAN', '🇨🇦', 'assets/flags/ca.png', 1, 10, 10,
      "### ### ####"),
  capeVerde('Cape Verde', 'CV', 'CPV', '🇨🇻', 'assets/flags/cv.png', 238, 7, 7,
      "### ####"),
  centralAfricanRepublic('Central African Republic', 'CF', 'CAF', '🇨🇫',
      'assets/flags/cf.png', 236, 7, 7, "## ## ## ##"),
  chad('Chad', 'TD', 'TCD', '🇹🇩', 'assets/flags/td.png', 235, 8, 8,
      "## ## ## ##"),
  chile('Chile', 'CL', 'CHL', '🇨🇱', 'assets/flags/cl.png', 56, 8, 8,
      "## ### ####"),
  china('China', 'CN', 'CHN', '🇨🇳', 'assets/flags/cn.png', 86, 11, 11,
      "#### #### ####"),
  colombia('Colombia', 'CO', 'COL', '🇨🇴', 'assets/flags/co.png', 57, 10, 10,
      "### ### ####"),
  comoros('Comoros', 'KM', 'COM', '🇰🇲', 'assets/flags/km.png', 269, 8, 8,
      "## ## ## ##"),
  congo('Congo (Congo-Brazzaville)', 'CG', 'COG', '🇨🇬', 'assets/flags/cg.png',
      242, 8, 8, "## ## ## ##"),
  congoKinshasa('Congo (Congo-Kinshasa)', 'CD', 'COD', '🇨🇩',
      'assets/flags/cd.png', 243, 8, 8, "## ## ## ##"),
  costaRica('Costa Rica', 'CR', 'CRI', '🇨🇷', 'assets/flags/cr.png', 506, 8, 8,
      "#### ####"),
  coteDIvoire('Côte d’Ivoire', 'CI', 'CIV', '🇨🇮', 'assets/flags/ci.png', 225,
      8, 8, "## ## ## ##"),
  croatia('Croatia', 'HR', 'HRV', '🇭🇷', 'assets/flags/hr.png', 385, 9, 9,
      "### ### ###"),
  cuba('Cuba', 'CU', 'CUB', '🇨🇺', 'assets/flags/cu.png', 53, 8, 8,
      "### ### ###"),
  cyprus('Cyprus', 'CY', 'CYP', '🇨🇾', 'assets/flags/cy.png', 357, 8, 8,
      "## ### ###"),
  czechRepublic('Czech Republic', 'CZ', 'CZE', '🇨🇿', 'assets/flags/cz.png',
      420, 9, 9, "### ### ###"),
  denmark('Denmark', 'DK', 'DNK', '🇩🇰', 'assets/flags/dk.png', 45, 8, 8,
      "## ## ## ##"),
  djibouti('Djibouti', 'DJ', 'DJI', '🇩🇯', 'assets/flags/dj.png', 253, 8, 8,
      "## ## ## ##"),
  dominica('Dominica', 'DM', 'DMA', '🇩🇲', 'assets/flags/dm.png', 1, 7, 7,
      "### ####"),
  dominicanRepublic('Dominican Republic', 'DO', 'DOM', '🇩🇴',
      'assets/flags/do.png', 1, 10, 10, "### ### ####"),
  ecuador('Ecuador', 'EC', 'ECU', '🇪🇨', 'assets/flags/ec.png', 593, 9, 9,
      "## ### ###"),
  egypt('Egypt', 'EG', 'EGY', '🇪🇬', 'assets/flags/eg.png', 20, 10, 10,
      "### ### ####"),
  elSalvador('El Salvador', 'SV', 'SLV', '🇸🇻', 'assets/flags/sv.png', 503, 8,
      8, "#### ####"),
  equatorialGuinea('Equatorial Guinea', 'GQ', 'GNQ', '🇬🇶',
      'assets/flags/gq.png', 240, 7, 7, "## ## ## ##"),
  eritrea('Eritrea', 'ER', 'ERI', '🇪🇷', 'assets/flags/er.png', 291, 7, 7,
      "## ### ###"),
  estonia('Estonia', 'EE', 'EST', '🇪🇪', 'assets/flags/ee.png', 372, 9, 9,
      "### ### ###"),
  ethiopia('Ethiopia', 'ET', 'ETH', '🇪🇹', 'assets/flags/et.png', 251, 9, 9,
      "## ### ###"),
  fiji(
      'Fiji', 'FJ', 'FJI', '🇫🇯', 'assets/flags/fj.png', 679, 7, 7, "## ####"),
  finland('Finland', 'FI', 'FIN', '🇫🇮', 'assets/flags/fi.png', 358, 10, 10,
      "### ### ###"),
  france('France', 'FR', 'FRA', '🇫🇷', 'assets/flags/fr.png', 33, 9, 9,
      "## ## ## ##"),
  gabon('Gabon', 'GA', 'GAB', '🇬🇦', 'assets/flags/ga.png', 241, 8, 8,
      "## ## ## ##"),
  gambia('Gambia', 'GM', 'GMB', '🇬🇲', 'assets/flags/gm.png', 220, 7, 7,
      "### ####"),
  georgia('Georgia', 'GE', 'GEO', '🇬🇪', 'assets/flags/ge.png', 995, 9, 9,
      "### ### ###"),
  germany('Germany', 'DE', 'DEU', '🇩🇪', 'assets/flags/de.png', 49, 11, 11,
      "### #######"),
  ghana('Ghana', 'GH', 'GHA', '🇬🇭', 'assets/flags/gh.png', 233, 9, 9,
      "## ### ####"),
  greece('Greece', 'GR', 'GRC', '🇬🇷', 'assets/flags/gr.png', 30, 10, 10,
      "### ### ####"),
  grenada('Grenada', 'GD', 'GRD', '🇬🇩', 'assets/flags/gd.png', 1, 7, 7,
      "### ####"),
  guatemala('Guatemala', 'GT', 'GTM', '🇬🇹', 'assets/flags/gt.png', 502, 8, 8,
      "#### ####"),
  guinea('Guinea', 'GN', 'GIN', '🇬🇳', 'assets/flags/gn.png', 224, 8, 8,
      "## ### ###"),
  guineaBissau('Guinea-Bissau', 'GW', 'GNB', '🇬🇼', 'assets/flags/gw.png', 245,
      7, 7, "## ### ###"),
  guyana('Guyana', 'GY', 'GUY', '🇬🇾', 'assets/flags/gy.png', 592, 7, 7,
      "### ####"),
  haiti('Haiti', 'HT', 'HTI', '🇭🇹', 'assets/flags/ht.png', 509, 8, 8,
      "## ## ####"),
  honduras('Honduras', 'HN', 'HND', '🇭🇳', 'assets/flags/hn.png', 504, 8, 8,
      "#### ####"),
  hungary('Hungary', 'HU', 'HUN', '🇭🇺', 'assets/flags/hu.png', 36, 9, 9,
      "## ### ###"),
  iceland('Iceland', 'IS', 'ISL', '🇮🇸', 'assets/flags/is.png', 354, 7, 7,
      "### ####"),
  india('India', 'IN', 'IND', '🇮🇳', 'assets/flags/in.png', 91, 10, 10,
      "#### ######"),
  indonesia('Indonesia', 'ID', 'IDN', '🇮🇩', 'assets/flags/id.png', 62, 11, 11,
      "## #### ####"),
  iran('Iran', 'IR', 'IRN', '🇮🇷', 'assets/flags/ir.png', 98, 10, 10,
      "### ### ####"),
  iraq('Iraq', 'IQ', 'IRQ', '🇮🇶', 'assets/flags/iq.png', 964, 10, 10,
      "### ### ####"),
  ireland('Ireland', 'IE', 'IRL', '🇮🇪', 'assets/flags/ie.png', 353, 9, 9,
      "## ### ####"),
  israel('Israel', 'IL', 'ISR', '🇮🇱', 'assets/flags/il.png', 972, 9, 9,
      "## ### ####"),
  italy('Italy', 'IT', 'ITA', '🇮🇹', 'assets/flags/it.png', 39, 10, 10,
      "## ### ####"),
  jamaica('Jamaica', 'JM', 'JAM', '🇯🇲', 'assets/flags/jm.png', 1, 7, 7,
      "### ####"),
  japan('Japan', 'JP', 'JPN', '🇯🇵', 'assets/flags/jp.png', 81, 10, 10,
      "## #### ####"),
  jordan('Jordan', 'JO', 'JOR', '🇯🇴', 'assets/flags/jo.png', 962, 9, 9,
      "### ### ####"),
  kazakhstan('Kazakhstan', 'KZ', 'KAZ', '🇰🇿', 'assets/flags/kz.png', 7, 10,
      10, "### ### ####"),
  kenya('Kenya', 'KE', 'KEN', '🇰🇪', 'assets/flags/ke.png', 254, 9, 9,
      "### ### ###"),
  kiribati('Kiribati', 'KI', 'KIR', '🇰🇮', 'assets/flags/ki.png', 686, 5, 5,
      "## ##"),
  koreaNorth('Korea, North', 'KP', 'PRK', '🇰🇵', 'assets/flags/kp.png', 850, 9,
      9, "### ### ####"),
  koreaSouth('Korea, South', 'KR', 'KOR', '🇰🇷', 'assets/flags/kr.png', 82, 10,
      10, "## #### ####"),
  kosovo('Kosovo', 'XK', 'XKX', '🇽🇰', 'assets/flags/xk.png', 383, 9, 9,
      "## ### ###"),
  kuwait('Kuwait', 'KW', 'KWT', '🇰🇼', 'assets/flags/kw.png', 965, 8, 8,
      "#### ####"),
  kyrgyzstan('Kyrgyzstan', 'KG', 'KGZ', '🇰🇬', 'assets/flags/kg.png', 996, 9,
      9, "### ### ###"),
  laos('Laos', 'LA', 'LAO', '🇱🇦', 'assets/flags/la.png', 856, 8, 8,
      "## ### ###"),
  latvia('Latvia', 'LV', 'LVA', '🇱🇻', 'assets/flags/lv.png', 371, 8, 8,
      "## ### ###"),
  lebanon('Lebanon', 'LB', 'LBN', '🇱🇧', 'assets/flags/lb.png', 961, 8, 8,
      "## ### ###"),
  lesotho('Lesotho', 'LS', 'LSO', '🇱🇸', 'assets/flags/ls.png', 266, 8, 8,
      "## ## ## ##"),
  liberia('Liberia', 'LR', 'LBR', '🇱🇷', 'assets/flags/lr.png', 231, 7, 7,
      "## ### ###"),
  libya('Libya', 'LY', 'LBY', '🇱🇾', 'assets/flags/ly.png', 218, 9, 9,
      "### ### ###"),
  liechtenstein('Liechtenstein', 'LI', 'LIE', '🇱🇮', 'assets/flags/li.png',
      423, 7, 7, "### ###"),
  lithuania('Lithuania', 'LT', 'LTU', '🇱🇹', 'assets/flags/lt.png', 370, 8, 8,
      "## ### ###"),
  luxembourg('Luxembourg', 'LU', 'LUX', '🇱🇺', 'assets/flags/lu.png', 352, 6,
      8, "## ## ## ##"),
  macedonia('Macedonia (North Macedonia)', 'MK', 'MKD', '🇲🇰',
      'assets/flags/mk.png', 389, 8, 8, "## ### ###"),
  madagascar('Madagascar', 'MG', 'MDG', '🇲🇬', 'assets/flags/mg.png', 261, 9,
      9, "## ## ## ##"),
  malawi('Malawi', 'MW', 'MWI', '🇲🇼', 'assets/flags/mw.png', 265, 8, 8,
      "## ## ## ##"),
  malaysia('Malaysia', 'MY', 'MYS', '🇲🇾', 'assets/flags/my.png', 60, 9, 9,
      "## ### ####"),
  maldives('Maldives', 'MV', 'MDV', '🇲🇻', 'assets/flags/mv.png', 960, 7, 7,
      "### ####"),
  mali('Mali', 'ML', 'MLI', '🇲🇱', 'assets/flags/ml.png', 223, 8, 8,
      "## ## ## ##"),
  malta('Malta', 'MT', 'MLT', '🇲🇹', 'assets/flags/mt.png', 356, 8, 8,
      "## #### ##"),
  marshallIslands('Marshall Islands', 'MH', 'MHL', '🇲🇭',
      'assets/flags/mh.png', 692, 7, 7, "### ####"),
  mauritania('Mauritania', 'MR', 'MRT', '🇲🇷', 'assets/flags/mr.png', 222, 8,
      8, "## ## ## ##"),
  mauritius('Mauritius', 'MU', 'MUS', '🇲🇺', 'assets/flags/mu.png', 230, 7, 7,
      "### ####"),
  mexico('Mexico', 'MX', 'MEX', '🇲🇽', 'assets/flags/mx.png', 52, 10, 10,
      "## #### ####"),
  micronesia('Micronesia', 'FM', 'FSM', '🇫🇲', 'assets/flags/fm.png', 691, 7,
      7, "### ####"),
  moldova('Moldova', 'MD', 'MDA', '🇲🇩', 'assets/flags/md.png', 373, 8, 8,
      "## ### ###"),
  monaco('Monaco', 'MC', 'MCO', '🇲🇨', 'assets/flags/mc.png', 377, 8, 8,
      "## ## ## ##"),
  mongolia('Mongolia', 'MN', 'MNG', '🇲🇳', 'assets/flags/mn.png', 976, 8, 8,
      "## ### ###"),
  montenegro('Montenegro', 'ME', 'MNE', '🇲🇪', 'assets/flags/me.png', 382, 8,
      8, "## ### ###"),
  morocco('Morocco', 'MA', 'MAR', '🇲🇦', 'assets/flags/ma.png', 212, 9, 9,
      "## ### ###"),
  mozambique('Mozambique', 'MZ', 'MOZ', '🇲🇿', 'assets/flags/mz.png', 258, 9,
      9, "## ### ###"),
  myanmar('Myanmar', 'MM', 'MMR', '🇲🇲', 'assets/flags/mm.png', 95, 8, 8,
      "## ### ###"),
  namibia('Namibia', 'NA', 'NAM', '🇳🇦', 'assets/flags/na.png', 264, 8, 8,
      "## ### ###"),
  nauru('Nauru', 'NR', 'NRU', '🇳🇷', 'assets/flags/nr.png', 674, 7, 7,
      "### ###"),
  nepal('Nepal', 'NP', 'NPL', '🇳🇵', 'assets/flags/np.png', 977, 10, 10,
      "## ### ###"),
  netherlands('Netherlands', 'NL', 'NLD', '🇳🇱', 'assets/flags/nl.png', 31, 9,
      9, "## ### ####"),
  newZealand('New Zealand', 'NZ', 'NZL', '🇳🇿', 'assets/flags/nz.png', 64, 8,
      8, "#### ### ###"),
  nicaragua('Nicaragua', 'NI', 'NIC', '🇳🇮', 'assets/flags/ni.png', 505, 8, 8,
      "#### ####"),
  niger('Niger', 'NE', 'NER', '🇳🇪', 'assets/flags/ne.png', 227, 8, 8,
      "## ## ## ##"),
  nigeria('Nigeria', 'NG', 'NGA', '🇳🇬', 'assets/flags/ng.png', 234, 10, 10,
      "### ### ####"),
  norway('Norway', 'NO', 'NOR', '🇳🇴', 'assets/flags/no.png', 47, 8, 8,
      "## ## ## ##"),
  oman('Oman', 'OM', 'OMN', '🇴🇲', 'assets/flags/om.png', 968, 8, 8,
      "#### ####"),
  pakistan('Pakistan', 'PK', 'PAK', '🇵🇰', 'assets/flags/pk.png', 92, 10, 10,
      "### ### ####"),
  palau('Palau', 'PW', 'PLW', '🇵🇼', 'assets/flags/pw.png', 680, 7, 7,
      "### ####"),
  panama('Panama', 'PA', 'PAN', '🇵🇦', 'assets/flags/pa.png', 507, 8, 8,
      "#### ####"),
  papuaNewGuinea('Papua New Guinea', 'PG', 'PNG', '🇵🇬', 'assets/flags/pg.png',
      675, 7, 7, "### ####"),
  paraguay('Paraguay', 'PY', 'PRY', '🇵🇾', 'assets/flags/py.png', 595, 9, 9,
      "### ### ###"),
  peru('Peru', 'PE', 'PER', '🇵🇪', 'assets/flags/pe.png', 51, 9, 9,
      "### ### ###"),
  philippines('Philippines', 'PH', 'PHL', '🇵🇭', 'assets/flags/ph.png', 63, 10,
      10, "#### ### ####"),
  poland('Poland', 'PL', 'POL', '🇵🇱', 'assets/flags/pl.png', 48, 9, 9,
      "### ### ###"),
  portugal('Portugal', 'PT', 'PRT', '🇵🇹', 'assets/flags/pt.png', 351, 9, 9,
      "### ### ###"),
  qatar('Qatar', 'QA', 'QAT', '🇶🇦', 'assets/flags/qa.png', 974, 8, 8,
      "#### ####"),
  romania('Romania', 'RO', 'ROU', '🇷🇴', 'assets/flags/ro.png', 40, 9, 9,
      "### ### ###"),
  russia('Russia', 'RU', 'RUS', '🇷🇺', 'assets/flags/ru.png', 7, 10, 10,
      "### ### ####"),
  rwanda('Rwanda', 'RW', 'RWA', '🇷🇼', 'assets/flags/rw.png', 250, 9, 9,
      "### ### ###"),
  saintKittsAndNevis('Saint Kitts and Nevis', 'KN', 'KNA', '🇰🇳',
      'assets/flags/kn.png', 1, 7, 7, "### ####"),
  saintLucia('Saint Lucia', 'LC', 'LCA', '🇱🇨', 'assets/flags/lc.png', 1, 7, 7,
      "### ####"),
  saintVincentAndTheGrenadines('Saint Vincent and the Grenadines', 'VC', 'VCT',
      '🇻🇨', 'assets/flags/vc.png', 1, 7, 7, "### ####"),
  samoa(
      'Samoa', 'WS', 'WSM', '🇼🇸', 'assets/flags/ws.png', 685, 5, 5, "## ###"),
  sanMarino('San Marino', 'SM', 'SMR', '🇸🇲', 'assets/flags/sm.png', 378, 8, 8,
      "## ## ## ##"),
  saoTomeAndPrincipe('Sao Tome and Principe', 'ST', 'STP', '🇸🇹',
      'assets/flags/st.png', 239, 7, 7, "### ####"),
  saudiArabia('Saudi Arabia', 'SA', 'SAU', '🇸🇦', 'assets/flags/sa.png', 966,
      9, 9, "### ### ####"),
  senegal('Senegal', 'SN', 'SEN', '🇸🇳', 'assets/flags/sn.png', 221, 9, 9,
      "## ### ###"),
  serbia('Serbia', 'RS', 'SRB', '🇷🇸', 'assets/flags/rs.png', 381, 8, 8,
      "## ### ###"),
  seychelles('Seychelles', 'SC', 'SYC', '🇸🇨', 'assets/flags/sc.png', 248, 7,
      7, "### ####"),
  sierraLeone('Sierra Leone', 'SL', 'SLE', '🇸🇱', 'assets/flags/sl.png', 232,
      8, 8, "## ### ###"),
  singapore('Singapore', 'SG', 'SGP', '🇸🇬', 'assets/flags/sg.png', 65, 8, 8,
      "#### ####"),
  slovakia('Slovakia', 'SK', 'SVK', '🇸🇰', 'assets/flags/sk.png', 421, 9, 9,
      "### ### ###"),
  slovenia('Slovenia', 'SI', 'SVN', '🇸🇮', 'assets/flags/si.png', 386, 8, 8,
      "## ### ###"),
  solomonIslands('Solomon Islands', 'SB', 'SLB', '🇸🇧', 'assets/flags/sb.png',
      677, 7, 7, "### ####"),
  somalia('Somalia', 'SO', 'SOM', '🇸🇴', 'assets/flags/so.png', 252, 8, 8,
      "## ### ###"),
  southAfrica('South Africa', 'ZA', 'ZAF', '🇿🇦', 'assets/flags/za.png', 27, 9,
      9, "### ### ####"),
  spain('Spain', 'ES', 'ESP', '🇪🇸', 'assets/flags/es.png', 34, 9, 9,
      "### ### ###"),
  sriLanka('Sri Lanka', 'LK', 'LKA', '🇱🇰', 'assets/flags/lk.png', 94, 10, 10,
      "## ### ####"),
  sudan('Sudan', 'SD', 'SDN', '🇸🇩', 'assets/flags/sd.png', 249, 9, 9,
      "### ### ###"),
  suriname('Suriname', 'SR', 'SUR', '🇸🇷', 'assets/flags/sr.png', 597, 7, 7,
      "### ####"),
  swaziland('Swaziland', 'SZ', 'SWZ', '🇸🇿', 'assets/flags/sz.png', 268, 8, 8,
      "## ## ## ##"),
  sweden('Sweden', 'SE', 'SWE', '🇸🇪', 'assets/flags/se.png', 46, 10, 10,
      "### ### ###"),
  switzerland('Switzerland', 'CH', 'CHE', '🇨🇭', 'assets/flags/ch.png', 41, 9,
      9, "### ### ###"),
  syria('Syria', 'SY', 'SYR', '🇸🇾', 'assets/flags/sy.png', 963, 10, 10,
      "### ### ####"),
  taiwan('Taiwan', 'TW', 'TWN', '🇹🇼', 'assets/flags/tw.png', 886, 9, 9,
      "### ### ###"),
  tajikistan('Tajikistan', 'TJ', 'TJK', '🇹🇯', 'assets/flags/tj.png', 992, 9,
      9, "### ### ###"),
  tanzania('Tanzania', 'TZ', 'TZA', '🇹🇿', 'assets/flags/tz.png', 255, 9, 9,
      "### ### ###"),
  thailand('Thailand', 'TH', 'THA', '🇹🇭', 'assets/flags/th.png', 66, 9, 9,
      "### ### ###"),
  timorLeste('Timor-Leste', 'TL', 'TLS', '🇹🇱', 'assets/flags/tl.png', 670, 8,
      8, "### ### ##"),
  togo('Togo', 'TG', 'TGO', '🇹🇬', 'assets/flags/tg.png', 228, 8, 8,
      "## ## ## ##"),
  tonga(
      'Tonga', 'TO', 'TON', '🇹🇴', 'assets/flags/to.png', 676, 5, 5, "## ###"),
  trinidadAndTobago('Trinidad and Tobago', 'TT', 'TTO', '🇹🇹',
      'assets/flags/tt.png', 1, 7, 7, "### ####"),
  tunisia('Tunisia', 'TN', 'TUN', '🇹🇳', 'assets/flags/tn.png', 216, 8, 8,
      "## ### ###"),
  turkey('Turkey', 'TR', 'TUR', '🇹🇷', 'assets/flags/tr.png', 90, 10, 10,
      "### ### ####"),
  turkmenistan('Turkmenistan', 'TM', 'TKM', '🇹🇲', 'assets/flags/tm.png', 993,
      8, 8, "## ### ###"),
  tuvalu('Tuvalu', 'TV', 'TUV', '🇹🇻', 'assets/flags/tv.png', 688, 5, 5,
      "### ##"),
  uganda('Uganda', 'UG', 'UGA', '🇺🇬', 'assets/flags/ug.png', 256, 9, 9,
      "### ### ###"),
  ukraine('Ukraine', 'UA', 'UKR', '🇺🇦', 'assets/flags/ua.png', 380, 9, 9,
      "## ### ####"),
  unitedArabEmirates('United Arab Emirates', 'AE', 'ARE', '🇦🇪',
      'assets/flags/ae.png', 971, 9, 9, "### ### ####"),
  unitedKingdom('United Kingdom', 'GB', 'GBR', '🇬🇧', 'assets/flags/gb.png',
      44, 10, 10, "#### ### ####"),
  unitedStates('United States', 'US', 'USA', '🇺🇸', 'assets/flags/us.png', 1,
      10, 10, "### ### ####"),
  uruguay('Uruguay', 'UY', 'URY', '🇺🇾', 'assets/flags/uy.png', 598, 8, 8,
      "### ## ## ##"),
  uzbekistan('Uzbekistan', 'UZ', 'UZB', '🇺🇿', 'assets/flags/uz.png', 998, 9,
      9, "## ### ###"),
  vanuatu('Vanuatu', 'VU', 'VUT', '🇻🇺', 'assets/flags/vu.png', 678, 7, 7,
      "## ###"),
  vaticanCity('Vatican City', 'VA', 'VAT', '🇻🇦', 'assets/flags/va.png', 379,
      8, 8, "#### ####"),
  venezuela('Venezuela', 'VE', 'VEN', '🇻🇪', 'assets/flags/ve.png', 58, 10, 10,
      "#### ### ####"),
  vietnam('Vietnam', 'VN', 'VNM', '🇻🇳', 'assets/flags/vn.png', 84, 10, 10,
      "### ### ####"),
  yemen('Yemen', 'YE', 'YEM', '🇾🇪', 'assets/flags/ye.png', 967, 10, 10,
      "### ### ####"),
  zambia('Zambia', 'ZM', 'ZMB', '🇿🇲', 'assets/flags/zm.png', 260, 9, 9,
      "### ### ###"),
  zimbabwe('Zimbabwe', 'ZW', 'ZWE', '🇿🇼', 'assets/flags/zw.png', 263, 9, 9,
      "### ### ###");

  final String _name;
  final String _alpha2;
  final String _alpha3;
  final String _flagEmoji;
  final String _flagImagePath;
  final int _dialCode;
  final int _minLength;
  final int _maxLength;
  final String _mask;

  const Country(
    this._name,
    this._alpha2,
    this._alpha3,
    this._flagEmoji,
    this._flagImagePath,
    this._dialCode,
    this._minLength,
    this._maxLength,
    this._mask,
  );

  String get flagImage => _flagImagePath;
  String get flag => _flagEmoji;
  String get dialCodeString => _dialCode.toString();
  String get maskString => _mask;
  String get name => _name;
  String get alpha2 => _alpha2;
  String get alpha3 => _alpha3;
  int get minLengthInt => _minLength;
  int get maxLengthInt => _maxLength;
}
